// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    FactionCard: typeof import('./src/components/FactionCard.vue')['default']
    FactionCheckbox: typeof import('./src/components/FactionCheckbox.vue')['default']
    FactionSetup: typeof import('./src/components/FactionSetup.vue')['default']
    GameSettings: typeof import('./src/components/GameSettings.vue')['default']
    GameSetup: typeof import('./src/components/GameSetup.vue')['default']
    MainNavLink: typeof import('./src/components/MainNavLink.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PlayerRejectedFactions: typeof import('./src/components/PlayerRejectedFactions.vue')['default']
    PlayerSettings: typeof import('./src/components/PlayerSettings.vue')['default']
    RandomizerTester: typeof import('./src/components/RandomizerTester.vue')['default']
    Seating: typeof import('./src/components/Seating.vue')['default']
    SeatingGenerator: typeof import('./src/components/SeatingGenerator.vue')['default']
  }
}

export { }
